name: Continuos Integration/Contiuos Delivery

on: [push]


jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar la última versión del código
        uses: actions/checkout@v4

      - name: Ejecutar las pruebas en un ambiente de Node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      